### ISSUE TITLE
Policy issue when used with "tf.exe". It still asks for code review even the folder is excluded. 

### ISSUE THREAD

**Issue by kriskoneru** [colindembovsky/ColinsALMCornerCheckinPolicies#15]
We are having an urgent issue. We have implemented checkin policy. The issue is when the developer is trying to check in using TF.exe and argument "Checkin". It always gives this error below in the screen shot

 We have excluded the folder path and it works fine using team explorer. 
But when the developer is trying to checkin using TF.exe all of a sudden it creates an issue shown in the screen shot below. we are using visual studio 2015 update 3. 

you can easily replicate the issue.  This is causing issues.  can you try to provide a solution. 

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\TF.exe checkin

![checkin-policy](https://user-images.githubusercontent.com/16949860/32742316-14b6c06e-c877-11e7-85bc-3c1963688be9.png)

**Comment by colindembovsky** [comment]
Hi @kriskoneru - you've configured the policy, which will be fired on any checkin - even from tf.exe. They issue isn't that the policy isn't working correctly - the error is that tf.exe can't evaluate the policy since it can't find the assembly with the policy (remember, policies are evaluated client-side, not server side). To resolve this, copy the ColinsAlmCheckinPolicies.dll to the same directory as tf.exe - that way the policy should be able to evaluate correctly.
