### ISSUE TITLE
Review id lost when immediate checkin with review id

### ISSUE THREAD

**Issue by leowijnhoven** [colindembovsky/ColinsALMCornerCheckinPolicies#22]
Reproduces (TFS2018 and Vs2015):
- create a code change and do checkin pending changes (set comment)
- start code review (add reviewer, the review is named after the comment)
- again do a checkin pending changes (and wait for the review to finish);
  (notice that the review id is shown as related item here)
- after the review is finished (looks good)
- checkin the file(s)
- the files are checked in BUT THE ASSOCIATED ITEM / REVIEW ID IS LOST
  the errors shown now, see below (screenshot and the text as shown in the VS2015 output window)
 (note that a workaround can be to (remove and) re-enter the review id after is has been finished)

![vs2015-reviewid-missing-id733916-tf237079](https://user-images.githubusercontent.com/7261666/35321438-3d1dfa2e-00e7-11e8-8bb5-5f7287eb5354.jpg)
](url)
ID 733916. Reason: TF237079: Team Foundation could not update the work item because it was already updated by another user, it does not exist, or you do not have permission to update it.
Failed to update the following work item:

**Comment by colindembovsky** [comment]
One of the limitations of the Code Review in VS is that you cannot update code. To update code you must create a new changeset. You're experiencing a symptom of this limitation: the code review is changed state but you still have it open in the view, so the work item is dirty. Not much I can do about this, though you should not be opening this request for such a long period of time (so that the work item doesn't get updated by another person).
